language: rust
rust:
  - stable
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all
  - travis_retry cargo test --verbose --all -- --ignored # Since some tests have rate to be failed.
